name: {{cookiecutter.repo_name}}
dependencies:
  - python={{cookiecutter.python_version}}
  - black
  - mypy
  - flake8
  - isort
  - pip
  - setuptools
  - wheel
  - typer
  - loguru
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - pip:
    - python-dotenv
    - awscli
    - -e .