name: {{cookiecutter.repo_name}}
dependencies:
  - python={{cookiecutter.python_version}}
  - ruff
  - mypy
  - pip
  - setuptools
  - wheel
  - typer
  - loguru
  - ipython
  - jupyter
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - scikit-learn
  - pip:
    - python-dotenv
    - awscli
    - -e .